### ISSUE TITLE
Tainted kernel node test fails if Intel Vt-d for directed I/O is enabled

### ISSUE THREAD

**Issue by AbhishekBandarupalle** [test-network-function/cnf-certification-test#332]
On New Mexico lab master nodes(master 1 and master2) - OS reported tainted kernels when Intel Vt-d for directed I/O was enabled. 
Disabling the option, made the taint to be 0 on `/proc/sys/kernel/tainted` 
I can reproduce the issue by enabling Vt-d for directed I/O - however there were two settings one under I/O configuration and one under CPU configuration for Intel VT-d, enabling the option on I/O config creates a kernel taint.

**Comment by AbhishekBandarupalle** [comment]
I see the taint value as 2048 - which is due to BIOS/firmware workarounds.

**Comment by greyerof** [comment]
So the kernel is actually tainted, and the TC is failing accordingly. If there's a way to know which kernel module introduced this kernel taint, the only way to "bypass" this failure is using the acceptedTaints field of the [TNF's config yaml file](https://github.com/test-network-function/cnf-certification-test/blob/fd6ce6f3bda2fa525b0b0d75300541b1cf246082/cnf-certification-test/tnf_config.yml#L20). If the taint doesn't come from any kernel module... then we should study whether it make sense to add another exception for this TC.

**Comment by edcdavid** [comment]
I see the following 2 root causes for iommu taints in the kernel code, seems like a legitimate bios issue. Maybe it would be solved by firmware upgrade? :
- " BIOS assigned incorrect VT-d unit for Intel(R) QuickData Technology device\n" and
- "Your BIOS is broken; bad RMRR [%#018Lx-%#018Lx]\n"
               "BIOS vendor: %s; Ver: %s; Product Version: %s\n",

**Comment by joeldavis84** [comment]
Is there a way to ignore a kernel taint of 2048 ("TAINT_FIRMWARE_WORKAROUND") ? I understand wanting to be aware of it  (especially by default) but for the purposes of CNF testing it might not be interesting information if we know it only pertains to an issue with the hardware the tests are being ran on rather than a problem with the CNF being deployed.

Let me know if I'm just not understanding something. I just have a partner that's already on the latest BIOS and is still getting a 2048 kernel taint.
